USE [master]
GO

/****** Object:  Database [MoviesProject]    Script Date: 14-03-2021 03:57:33 ******/
CREATE DATABASE [MoviesProject]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MoviesProject', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MoviesProject.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MoviesProject_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MoviesProject_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MoviesProject].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MoviesProject] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MoviesProject] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MoviesProject] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MoviesProject] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MoviesProject] SET ARITHABORT OFF 
GO

ALTER DATABASE [MoviesProject] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MoviesProject] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MoviesProject] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MoviesProject] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MoviesProject] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MoviesProject] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MoviesProject] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MoviesProject] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MoviesProject] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MoviesProject] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MoviesProject] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MoviesProject] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MoviesProject] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MoviesProject] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MoviesProject] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MoviesProject] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MoviesProject] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MoviesProject] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MoviesProject] SET  MULTI_USER 
GO

ALTER DATABASE [MoviesProject] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MoviesProject] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MoviesProject] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MoviesProject] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MoviesProject] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MoviesProject] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MoviesProject] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MoviesProject] SET  READ_WRITE 
GO

